server:
  error:
    include-binding-errors: always
    include-stacktrace: never
    include-message: always
  port: 8080
  servlet:
    context-path: /car-rental/api


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/leccarrentaldb
    username: techpro
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLMyISAMDialect
        format_sql: true
    show-sql: true
